export const COLLAPSE_NAV_MENU = 'COLLAPSE_NAV_MENU';
export const EXPAND_NAV_MENU = 'EXPAND_NAV_MENU';
export const TOGGLE_NAV_MENU = 'TOGGLE_NAV_MENU';

export const EXPAND_MENU = 'EXPAND_MENU';
export const EXPAND_ACTIVATED_MENU = 'EXPAND_ACTIVATED_MENU';