export default [{
    text: 'Button',
    children: [{
        text: 'RaisedButton',
        route: '/components/RaisedButton'
    }, {
        text: 'FlatButton',
        route: '/components/FlatButton'
    }, {
        text: 'GhostButton',
        route: '/components/GhostButton'
    }, {
        text: 'IconButton',
        route: '/components/IconButton'
    }, {
        text: 'AnchorButton',
        route: '/components/AnchorButton'
    }]
}, {
    text: 'Anchor',
    children: [{
        text: 'Anchor',
        route: '/components/Anchor'
    }, {
        text: 'IconAnchor',
        route: '/components/IconAnchor'
    }]
}, {
    text: 'Date',
    children: [{
        text: 'DatePicker',
        route: '/components/DatePicker'
    }, {
        text: 'DateField',
        route: '/components/DateField'
    }, {
        text: 'MonthPicker',
        route: '/components/MonthPicker'
    }, {
        text: 'DateRangePicker',
        route: '/components/DateRangePicker'
    }, {
        text: 'DateRangeField',
        route: '/components/DateRangeField'
    }, {
        text: 'TimePicker',
        route: '/components/TimePicker'
    }, {
        text: 'DateTimePicker',
        route: '/components/DateTimePicker'
    }, {
        text: 'MaterialDatePicker',
        route: '/components/MaterialDatePicker'
    }, {
        text: 'MaterialDateTimePicker',
        route: '/components/MaterialDateTimePicker'
    }, {
        text: 'MaterialTimePicker',
        route: '/components/MaterialTimePicker'
    }, {
        text: 'MaterialDateRangePicker',
        route: '/components/MaterialDateRangePicker'
    }, {
        text: 'MaterialMonthPicker',
        route: '/components/MaterialMonthPicker'
    }]
}, {
    text: 'Field',
    children: [{
        text: 'TextField',
        route: '/components/TextField'
    }, {
        text: 'CascaderSelect',
        route: '/components/CascaderSelect'
    }, {
        text: 'MaterialCascaderSelect',
        route: '/components/MaterialCascaderSelect'
    }, {
        text: 'TextArea',
        route: '/components/TextArea'
    }, {
        text: 'LocalAutoComplete',
        route: '/components/LocalAutoComplete'
    }, {
        text: 'RemoteAutoComplete',
        route: '/components/RemoteAutoComplete'
    }, {
        text: 'DropdownSelect',
        route: '/components/DropdownSelect'
    }, {
        text: 'MultipleSelect',
        route: '/components/MultipleSelect'
    }, {
        text: 'Checkbox',
        route: '/components/Checkbox'
    }, {
        text: 'RadioGroup',
        route: '/components/RadioGroup'
    }, {
        text: 'ButtonCheckbox',
        route: '/components/ButtonCheckbox'
    }, {
        text: 'ButtonRadioGroup',
        route: '/components/ButtonRadioGroup'
    }, {
        text: 'ButtonRadioSelect',
        route: '/components/ButtonRadioSelect'
    }, {
        text: 'Switcher',
        route: '/components/Switcher'
    }, {
        text: 'Slider',
        route: '/components/Slider'
    }, {
        text: 'EditableField',
        route: '/components/EditableField'
    }, {
        text: 'FlashNumber',
        route: '/components/FlashNumber'
    }, {
        text: 'Transfer',
        route: '/components/Transfer'
    }, {
        text: 'TreeSelect',
        route: '/components/TreeSelect'
    }, {
        text: 'TagField',
        route: '/components/TagField'
    }, {
        text: 'DynamicRenderTagField',
        route: '/components/DynamicRenderTagField'
    }, {
        text: 'Rate',
        route: '/components/Rate'
    }, {
        text: 'EditableSelect',
        route: '/components/EditableSelect'
    }, {
        text: 'MaterialTextField',
        route: '/components/MaterialTextField'
    }, {
        text: 'MaterialDropdownSelect',
        route: '/components/MaterialDropdownSelect'
    }, {
        text: 'MaterialLocalAutoComplete',
        route: '/components/MaterialLocalAutoComplete'
    }, {
        text: 'MaterialTextArea',
        route: '/components/MaterialTextArea'
    }, {
        text: 'MaterialEditableSelect',
        route: '/components/MaterialEditableSelect'
    }, {
        text: 'MaterialTreeSelect',
        route: '/components/MaterialTreeSelect'
    }, {
        text: 'DownloadField',
        route: '/components/DownloadField'
    }]
}, {
    text: 'Filter',
    children: [{
        text: 'DropdownFilter',
        route: '/components/DropdownFilter'
    }, {
        text: 'MaterialDropdownFilter',
        route: '/components/MaterialDropdownFilter'
    }, {
        text: 'AutoCompleteFilter',
        route: '/components/AutoCompleteFilter'
    }, {
        text: 'MaterialAutoCompleteFilter',
        route: '/components/MaterialAutoCompleteFilter'
    }]
}, {
    text: 'Progress',
    children: [{
        text: 'CircleProgress',
        route: '/components/CircularProgress'
    }, {
        text: 'LinearProgress',
        route: '/components/linearProgress'
    }]
}, {
    text: 'Layout',
    children: [{
        text: 'Crumbs',
        route: '/components/Crumbs'
    }, {
        text: 'Paper',
        route: '/components/Paper'
    }, {
        text: 'Widget',
        route: '/components/Widget'
    }, {
        text: 'List',
        route: '/components/List'
    }, {
        text: 'GroupList',
        route: '/components/GroupList'
    }, {
        text: 'DynamicRenderList',
        route: '/components/DynamicRenderList'
    }, {
        text: 'CascaderList',
        route: '/components/CascaderList'
    }, {
        text: 'Tab',
        route: '/components/Tab'
    }, {
        text: 'Accordion',
        route: '/components/Accordion'
    }, {
        text: 'Table',
        route: '/components/Table'
    }, {
        text: 'Waterfall',
        route: '/components/Waterfall'
    }, {
        text: 'Grid',
        route: '/components/Grid'
    }, {
        text: 'GroupGrid',
        route: '/components/GroupGrid'
    }, {
        text: 'Tree',
        route: '/components/Tree'
    }, {
        text: 'Dropdown',
        route: '/components/Dropdown'
    }, {
        text: 'MaterialDropdown',
        route: '/components/MaterialDropdown'
    }, {
        text: 'Pagging',
        route: '/components/Pagging'
    }, {
        text: 'BriefPagging',
        route: '/components/BriefPagging'
    }, {
        text: 'MaterialProvider',
        route: '/components/MaterialProvider'
    }, {
        text: 'TimeLine',
        route: '/components/TimeLine'
    }]
}, {
    text: 'Loading',
    children: [{
        text: 'CircularLoading',
        route: '/components/CircularLoading'
    }, {
        text: 'SpanLoading',
        route: '/components/SpanLoading'
    }, {
        text: 'PageLoading',
        route: '/components/PageLoading'
    }]
}, {
    text: 'Draggable',
    children: [{
        text: 'DraggableList',
        route: '/components/DraggableList'
    }, {
        text: 'DraggableGrid',
        route: '/components/DraggableGrid'
    }, {
        text: 'DraggableTree',
        route: '/components/DraggableTree'
    }]
}, {
    text: 'Stepper',
    children: [{
        text: 'ArrowStep',
        route: '/components/ArrowStep'
    }, {
        text: 'RoundStep',
        route: '/components/RoundStep'
    }, {
        text: 'ListStep',
        route: '/components/ListStep'
    }, {
        text: 'DotStep',
        route: '/components/DotStep'
    }, {
        text: 'PointStep',
        route: '/components/PointStep'
    }, {
        text: 'VerticalPointStep',
        route: '/components/VerticalPointStep'
    }]
}, {
    text: 'Pop',
    children: [{
        text: 'Dialog',
        route: '/components/Dialog'
    }, {
        text: 'Popup',
        route: '/components/Popup'
    }, {
        text: 'Popover',
        route: '/components/Popover'
    }, {
        text: 'Drawer',
        route: '/components/Drawer'
    }, {
        text: 'Tip',
        route: '/components/Tip'
    }, {
        text: 'Toast',
        route: '/components/Toast'
    }, {
        text: 'Notification',
        route: '/components/Notification'
    }, {
        text: 'Guide',
        route: '/components/Guide'
    }]
}, {
    text: 'Media',
    children: [{
        text: 'LazyImage',
        route: '/components/LazyImage'
    }, {
        text: 'ColorPicker',
        route: '/components/ColorPicker'
    }, {
        text: 'HuePicker',
        route: '/components/HuePicker'
    }, {
        text: 'TransparencyPicker',
        route: '/components/TransparencyPicker'
    }]
}];
