export default [{
    text: 'Buttons',
    children: [{
        text: 'RaisedButton',
        route: '/components/RaisedButton'
    }, {
        text: 'FlatButton',
        route: '/components/FlatButton'
    }, {
        text: 'GhostButton',
        route: '/components/GhostButton'
    }, {
        text: 'IconButton',
        route: '/components/IconButton'
    }, {
        text: 'IconAnchor',
        route: '/components/IconAnchor'
    }]
}, {
    text: 'Popup',
    children: [{
        text: 'Dialog',
        route: '/components/Dialog'
    }, {
        text: 'Popup',
        route: '/components/Popup'
    }]
}, {
    text: 'Date',
    children: [{
        text: 'DatePicker',
        route: '/components/DatePicker'
    }, {
        text: 'DateRangePicker',
        route: '/components/DateRangePicker'
    }, {
        text: 'TimePicker',
        route: '/components/TimePicker'
    }, {
        text: 'DateTimePicker',
        route: '/components/DateTimePicker'
    }]
}, {
    text: 'Fields',
    children: [{
        text: 'TextField',
        route: '/components/TextField'
    }, {
        text: 'TextArea',
        route: '/components/TextArea'
    }, {
        text: 'LocalAutoComplete',
        route: '/components/LocalAutoComplete'
    }, {
        text: 'RemoteAutoComplete',
        route: '/components/RemoteAutoComplete'
    }, {
        text: 'DropdownSelect',
        route: '/components/DropdownSelect'
    }, {
        text: 'MultipleSelect',
        route: '/components/MultipleSelect'
    }, {
        text: 'Checkbox',
        route: '/components/Checkbox'
    }, {
        text: 'RadioGroup',
        route: '/components/RadioGroup'
    }, {
        text: 'ButtonCheckbox',
        route: '/components/ButtonCheckbox'
    }, {
        text: 'ButtonRadioGroup',
        route: '/components/ButtonRadioGroup'
    }, {
        text: 'Switcher',
        route: '/components/Switcher'
    }, {
        text: 'Slider',
        route: '/components/Slider'
    }, {
        text: 'EditableField',
        route: '/components/EditableField'
    }, {
        text: 'FlashNumber',
        route: '/components/FlashNumber'
    }, {
        text: 'Transfer',
        route: '/components/Transfer'
    }, {
        text: 'TreeSelect',
        route: '/components/TreeSelect'
    }, {
        text: 'Tree',
        route: '/components/Tree'
    }]
}, {
    text: 'Progress',
    children: [{
        text: 'CircleProgress',
        route: '/components/CircularProgress'
    }, {
        text: 'LinearProgress',
        route: '/components/linearProgress'
    }]
}, {
    text: 'Layout',
    children: [{
        text: 'Paper',
        route: '/components/Paper'
    }, {
        text: 'Widget',
        route: '/components/Widget'
    }, {
        text: 'List',
        route: '/components/List'
    }, {
        text: 'Tab',
        route: '/components/Tab'
    }, {
        text: 'Accordion',
        route: '/components/Accordion'
    }, {
        text: 'Table',
        route: '/components/Table'
    }, {
        text: 'Waterfall',
        route: '/components/Waterfall'
    }]
}, {
    text: 'Stepper',
    children: [{
        text: 'ArrowStep',
        route: '/components/ArrowStep'
    }, {
        text: 'RoundStep',
        route: '/components/RoundStep'
    }, {
        text: 'ListStep',
        route: '/components/ListStep'
    }]
}, {
    text: 'Message',
    children: [{
        text: 'Toaster',
        route: '/components/Toaster'
    }, {
        text: 'Tip',
        route: '/components/Tip'
    }]
}, {
    text: 'TimeLine',
    route: '/components/TimeLine'
}, {
    text: 'Rate',
    route: '/components/Rate'
}, {
    text: 'Loading',
    children: [{
        text: 'SpanLoading',
        route: '/components/SpanLoading'
    }, {
        text: 'CircularLoading',
        route: '/components/CircularLoading'
    }]
}, {
 text: 'Cascader',
 route: '/components/Cascader'
 }];