const ACTIVATING = 'ACTIVATING';
const RUNNING = 'RUNNING';
const ACTIVE = 'ACTIVE';
const DEACTIVATING = 'DEACTIVATING';
const INACTIVE = 'INACTIVE';

export default {
	ACTIVATING,
	RUNNING,
	ACTIVE,
	DEACTIVATING,
	INACTIVE
}